server {
    listen 80;
    listen [::]:80;

    server_name nayanap.site www.nayanap.site;

    root /var/www/nayanap.site/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/nayanap.site.access.log;
    error_log  /var/log/nginx/nayanap.site.error.log;
}
